baseURL = 'https://f0rg-02.github.io/blog'
languageCode = "en-us"
title = "f0rg's blog"
theme = ["m10c"]


[params]
  avatar = "img/avatar.webp"
  author = "Alex"
  description = "A blog about whatever I feel like writing. This can range from rants/opinions, hardware, infosec, food, backpacks, etc."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/f0rg-02"

  [[params.social]]
    icon = "mastodon"
    name = "Mastodon"
    url = "https://infosec.exchange/@alex_02"

[permalinks]
	[permalinks.page]
		posts = '/articles/:year/:month/:slug/'
		about = '/about/:slug/'
	[permalinks.section]
    		posts = '/articles/'
    		about = '/about/'
	
[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
[[menus.main]]
    name = 'About'
    pageRef = '/about/'
    wegight = 2

